# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.10'

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: mkPeq8k8Csb/iyacVc003teVckiiVzUfPTJuBg1WxsZodZQnBNY3wFjyglXcOie4gCcB1G0GaipFwgQBgbdlBNrnOzkqhyK7KI0dT03xJ8PCcVjJdEq7qiERn2/pnxGTUkrxwXGGRgyJ+oFywCS8rl9cRHq1CA4Xd6F7UY1gAMTia06Qpp/oE0TDFKXvvusoaXZyUoyOGtfwM5/ZJ7qWXrdyJRg07SIeVsQxs/S58/iy4xcRk+fVl58zYLUasIMyBMyNde8qoW/+ccwz6F63C0NJjLDsKan2auHa3hTDm1HOiMk+/o9LStWDEcy6ZEi4eG/DmoZma8Z+8DTRRQxE4om0sZ7SDtxR4vH/a2i4BCz7tPrfPul5676IdgRXDpKFjyzrr2mxiFs3XwUpxSrGW/LsWwVlOFPyIaRa44w8lFXvDaWvNP1ca3J1xQQVaG6QJbH2TbPWi/JVviy+G90WJziHGRqWmplpJV3ZOjkVRTjf13ENrIj+1j57n+S/hR7nLjUAJYvy2jmEQ+bMmPVC/0lV4Sk2bpAXUlUweKW5hIc4qfXVjvUWQ0x1zNntsP8ZUVDN4MCx2FBlPsLu9+mjuT9HKGpkKqAroR60V9TjWcbXM64vmld96HxJLCFLdfsqp1d/X05DN3VOpNkU8bbJFQYxGU9UZy3D1n6SlidohuE=
    # SAUCE_TOKENS
    - secure: OF6JEWLnHWnmZvkM5CZ/lvpLxEbN29j7HmHBM8YoSNSoyyW2BtycYB3UpBcg7pjBU6UopwmPTawjgjukC1hsR0TKqoTWGfgBxGYwBR4O0fARgDcYMltwpr0I/SqEx8nzY71jCKevNc4XfA/Q9EXEr5INBpIzbw5o+7RyBM5M6GOd1kykOl6hL0MehFMpUzmDhsIM1dTRvr9qEWorjlH2RPYx2pv2u7pJnnGKrCxQnQ3Mh4HOrkixcN1gUssX/iLS7JzsJm80yKff6fUtVM/AGifqSkgg9ICedd7T6zPP9Z6D74b6wEv+DceLpC/0YnK1f+jcWKV1HZnXro2QB2VMXWk/VRxHPh2qwU/Ao0jPajRx6Vm70GeYw+BkJKN2f0Tpu7uMvfUwmBOJhBLXvtwNAg9qSCrrgvf4LIa45QEsh8h7NknP8/Qs9rwqjAj4/69FR0nM4oHpYlAngtMCtFX/S0X3FX9TiGSpY0Sa6zv4P/ZRwbsDRt4uKVpYq+2yKU2XIHHN6D6XFOtQF059u7JswmqsDNMKPomOF5Z8xsY3iiqIbA8GDfwAXnINq5rJ0IdLvtdmLGGG5szFhGrp8cWzTGbEeBE92pD9lIbUw/UC3Eyyc2CveneCzlpdeafZ2D4T9uwfqO9JGlxS33xv9i7kk4S6huKTSpqv1pgoAvrg/Ac=
    - secure: jfKeATf5vyI4md2LEL4Bbvo5yx5kqryJ3Qxsl7LavpeIeiZaWud13p6KvqtjNDDvx2ZgPO0jlqShTWnyGcqvQbfGnmvynmUDLNvNUpk55Vnh/QMQYWoW25TZJ0k/1tqQRriTq+e3Hqa9gyhLYb8Gf6BunCZ8EZdompehPcszCZVZwWAY6NeiqGQ8sIdjg4Jrf+kPU7b1qMpt3jgGqYvNnI9RAnd6exZt9SIJ690KSn/NVHx7/6VdCJv2in6/irT3WtMjNxRR1RUi1JI+PU++BUmbtWPQS7dmvlzQ73Xh5hXlzPohhEs96g2kMp95/Jwg60tzXE94sa9b/m8yWNhL+MN/mAxCfIKa/FjojjI7y8bFB5Mh3l9ul8N2Mb3QRaaOC1rPO9v4iJVyqUKWMxtUfgmg+VtsqgyyZTb8QT1IrsCUoX88o8VwpTgkb/oRXIPXVLwBuVAslmlbOa/TK0bQin+22vghA/TYr4keP7Ju70RRtlaHKe7VJH2YoB1pTsfhpgDHXuVFu8atFFzlv0gd3xm8PKy/Cvf69/iS+4OpzDL/DutIHLigYjerLFAF9yBvWxF4gvF7NHc8psQ36t/shfeJA7mB77E5PZoLZ+IjBJhctEGpwQ47DB66K6LGYtrMcvPdIUJqlqij+nsjJTOXrgxp/gsvEQ7yWMegd+BkElk=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: QWClUfQNyjteZfuxZjfY1lRCC9a8vvrA+3LXDjxuqeMltVjq2vpKxZL/7S30zu5n+4JyWZj9a7gsr/N6slwoTDPjX01uaAf/CC9ayGeYSv/QTTyeowwdry3EsjmIHagiwiYMoyS3+DAXoxoePq9lhks6aV5XA3Rlld7ZZfkI3KKln52YLYzaonaaC3RlMeScmROsHy4LbxS1VDhtRJgJcCVlb6EV+EyhhdN6VP7An9uJuEZGvkhiE/Zs+1wsLSV59lmjqPx+FISiQgGdRCy9Dyl1HTLQ+2gpiEdh1OSFTXGFJdBWtZgKrGz+S1KArDK8X+h8GuMuE0kfP6dDCtSfIB1d6kLV7t9pwT/KaS4NqaCYTrWMET3gcn2M3qluWU7NgDngG7Bi75Ya5SHC56YiLcpaWU1lF7wZe7/bWX/z+s48RsYgHP0L+MTa3FfE0CWtPejbVHI1WSLSUX2qwa7KUGTj9v+CQUOwzj6cgMVZkwvki40xfhYJTG1c2IEfx054cgWbhQV4ijW2vb+vKfDqVMlgjBukjFGTul+e28e++IhY7i9j2lijkijpAcCal3wue/9mWFkoXlm9VLWoSk4g/ko8a8DCiCsjQJC/d9iPE+LirxkGRWgkHDvAn0AAEyRB/45bP9Nv/G2B3vZBxljpD/Lxli337R4okh6mMrfxVuY=

# Cloud testing
after_deploy:
  - npm install
  - npm run test-cloud
